#!/usr/bin/env python3
# Generates the MIR backend host-ABI interop test: aggregates of many shapes
# passed and returned by value between JIT code (slimcc-mir-run) and
# host-compiled code (a shared library built by the host compiler).
#
#   gen.py OUTDIR [--bitint]  (--bitint: the host compiler has _BitInt)
#                   ->  OUTDIR/abi.h  (types, fill/check, shared by both sides)
#                       OUTDIR/host.c (host-compiled half)
#                       OUTDIR/jit.c  (JIT half + main)
#
# Every case runs in both directions: JIT calling host functions (call-site
# lowering) and host calling JIT functions through pointers (definition-side
# lowering), including register exhaustion and variadic positions.
import os
import sys


def arr(ctype, name, n):
    return [(f"{name}[{i}]", ctype) for i in range(n)]


def bits(name, w, signed=False):
    return [(name, ("s" if signed else "u") + f"bits{w}")]


# (name, struct/union body, scalar members to fill and check, flags)
# Flags: union (fill/check the first member only), hfa (an aarch64 homogeneous
# floating-point aggregate: variadic passing is a documented gap there),
# bitint (needs _BitInt support in the host compiler).
TYPES = [
    ("C1", "char a;", [("a", "char")], ""),
    ("S1", "short a;", [("a", "short")], ""),
    ("C3", "char a[3];", arr("char", "a", 3), ""),
    ("I1", "int a;", [("a", "int")], ""),
    ("C5", "char a[5];", arr("char", "a", 5), ""),
    ("C6", "char a[6];", arr("char", "a", 6), ""),
    ("C7", "char a[7];", arr("char", "a", 7), ""),
    ("U2", "unsigned a, b;", [("a", "unsigned"), ("b", "unsigned")], ""),
    ("I3", "int a, b, c;", [("a", "int"), ("b", "int"), ("c", "int")], ""),
    ("S7", "short a[7];", arr("short", "a", 7), ""),
    ("L2", "long a, b;", [("a", "long"), ("b", "long")], ""),
    ("L3", "long a, b, c;", [("a", "long"), ("b", "long"), ("c", "long")], ""),
    ("CI", "char a; int b;", [("a", "char"), ("b", "int")], ""),
    ("CD", "char a; double b;", [("a", "char"), ("b", "double")], ""),
    ("F1", "float a;", [("a", "float")], "hfa"),
    ("F2", "float a, b;", [("a", "float"), ("b", "float")], "hfa"),
    ("F3", "float a[3];", arr("float", "a", 3), "hfa"),
    ("F4", "float a, b, c, d;", [(c, "float") for c in "abcd"], "hfa"),
    ("F5", "float a[5];", arr("float", "a", 5), ""),
    ("D1", "double a;", [("a", "double")], "hfa"),
    ("D2", "double a, b;", [("a", "double"), ("b", "double")], "hfa"),
    ("D3", "double a[3];", arr("double", "a", 3), "hfa"),
    ("D4", "double a, b, c, d;", [(c, "double") for c in "abcd"], "hfa"),
    ("NF", "struct { float x, y; } p; float z;",
     [("p.x", "float"), ("p.y", "float"), ("z", "float")], "hfa"),
    ("DL", "double a; long b;", [("a", "double"), ("b", "long")], ""),
    ("LD", "long a; double b;", [("a", "long"), ("b", "double")], ""),
    ("FI", "float a; int b;", [("a", "float"), ("b", "int")], ""),
    ("IF", "int a; float b;", [("a", "int"), ("b", "float")], ""),
    ("FFI", "float a, b; int c;", [("a", "float"), ("b", "float"), ("c", "int")], ""),
    ("IFF", "int a; float b, c;", [("a", "int"), ("b", "float"), ("c", "float")], ""),
    ("DF", "double a; float b;", [("a", "double"), ("b", "float")], ""),
    ("Q1", "long double a;", [("a", "long double")], "hfa"),
    ("Q2", "long double a, b;", [("a", "long double"), ("b", "long double")], "hfa"),
    ("UI", "int i; float f;", [("i", "int")], "union"),
    ("UF", "float f; float g[2];", arr("float", "g", 2), "union hfa"),
    ("BF", "unsigned a : 3; unsigned b : 7; int c : 12;",
     bits("a", 3) + bits("b", 7) + bits("c", 12, True), ""),
    ("BF2", "unsigned long long a : 40; unsigned b : 20; char c;",
     bits("a", 40) + bits("b", 20) + [("c", "char")], ""),
    ("B100", "_BitInt(100) a;", [("a", "bitint100")], "bitint"),
    ("B130", "_BitInt(130) a;", [("a", "bitint130")], "bitint"),
    ("B200", "_BitInt(200) a;", [("a", "bitint200")], "bitint"),
    ("CB", "char c; _BitInt(100) a;", [("c", "char"), ("a", "bitint100")], "bitint"),
]


def value(ctype, i):
    """C expression for scalar i's value, as a function of `seed`."""
    k = f"(seed * 31 + {i * 7 + 1})"
    if ctype in ("float", "double", "long double"):
        return f"({ctype})({k} + 0.5)"
    if ctype.startswith("ubits"):
        w = int(ctype[5:])
        return f"({k} & {(1 << w) - 1}ULL)"
    if ctype.startswith("sbits"):
        w = int(ctype[5:])
        return f"(({k} & {(1 << (w - 1)) - 1}) - {1 << (w - 2)})"
    if ctype.startswith("bitint"):
        # Exercise the high chunks too.
        return f"(((_BitInt({ctype[6:]})){k} << 70) + {k})"
    if ctype == "char":
        return f"(char)({k} & 0x7f)"
    return f"({ctype})({k} * 1000003LL)"


def gen_header(out, bitint):
    w = out.write
    w("// Generated by test/mir-abi/gen.py - do not edit.\n")
    if bitint:
        w("#define HAVE_BITINT 1\n")
    w("#include <stdarg.h>\n#include <string.h>\n\n")
    for name, body, members, flags in TYPES:
        kind = "union" if "union" in flags else "struct"
        guard = "bitint" in flags
        if guard:
            w("#ifdef HAVE_BITINT\n")
        w(f"typedef {kind} {name} {{ {body} }} {name};\n")
        w(f"static void fill_{name}({name} *v, int seed) {{\n")
        w("  memset(v, 0, sizeof *v);\n")
        for i, (lv, ct) in enumerate(members):
            w(f"  v->{lv} = {value(ct, i)};\n")
        w("}\n")
        w(f"static int check_{name}({name} *v, int seed) {{\n  return 1")
        for i, (lv, ct) in enumerate(members):
            w(f"\n    && v->{lv} == {value(ct, i)}")
        w(";\n}\n")
        w(f"static {name} mk_{name}(int seed) {{ {name} v; fill_{name}(&v, seed); return v; }}\n")
        if guard:
            w("#endif\n")
        w("\n")


def sig(name, prefix):
    """Function signatures shared by the host (h_*) and JIT (j_*) sides."""
    T = name
    p = prefix
    return {
        "ret": f"{T} {p}_ret_{T}(int seed)",
        "arg": f"int {p}_arg_{T}({T} v, int seed)",
        "two": f"int {p}_two_{T}({T} a, {T} b, int seed)",
        "mi": f"int {p}_mi_{T}(long i0, long i1, long i2, long i3, long i4, {T} v, long i5, int seed)",
        "m7": f"int {p}_m7_{T}(long i0, long i1, long i2, long i3, long i4, long i5, long i6, {T} v, long i7, int seed)",
        "mf": f"int {p}_mf_{T}(double d0, double d1, double d2, double d3, double d4, double d5, double d6, {T} v, double d7, int seed)",
        "rmi": f"{T} {p}_rmi_{T}(long i0, long i1, long i2, long i3, long i4, long i5, int seed)",
        "va": f"int {p}_va_{T}(int seed, int n, ...)",
        "va1": f"int {p}_va1_{T}(int seed, ...)",
        "vam": f"int {p}_vam_{T}(int seed, ...)",
    }


def bodies(T, p):
    s = sig(T, p)
    return f"""{s['ret']} {{ return mk_{T}(seed); }}
{s['arg']} {{ return check_{T}(&v, seed); }}
{s['two']} {{ return check_{T}(&a, seed) && check_{T}(&b, seed + 1); }}
{s['mi']} {{
  return i0 == 1 && i1 == 2 && i2 == 3 && i3 == 4 && i4 == 5 && i5 == 6 && check_{T}(&v, seed);
}}
{s['m7']} {{
  return i0 == 1 && i1 == 2 && i2 == 3 && i3 == 4 && i4 == 5 && i5 == 6 && i6 == 7 && i7 == 8
      && check_{T}(&v, seed);
}}
{s['mf']} {{
  return d0 == 1.5 && d1 == 2.5 && d2 == 3.5 && d3 == 4.5 && d4 == 5.5 && d5 == 6.5
      && d6 == 7.5 && d7 == 8.5 && check_{T}(&v, seed);
}}
{s['rmi']} {{
  if (!(i0 == 1 && i1 == 2 && i2 == 3 && i3 == 4 && i4 == 5 && i5 == 6))
    return mk_{T}(seed + 99);
  return mk_{T}(seed);
}}
{s['va']} {{
  va_list ap;
  int ok = 1;
  va_start(ap, n);
  for (int k = 0; k < n; k++) {{
    {T} v = va_arg(ap, {T});
    ok = ok && check_{T}(&v, seed + k);
  }}
  ok = ok && va_arg(ap, int) == 12345;
  va_end(ap);
  return ok;
}}
{s['va1']} {{
  va_list ap;
  va_start(ap, seed);
  {T} a = va_arg(ap, {T});
  int i = va_arg(ap, int);
  {T} b = va_arg(ap, {T});
  int ok = check_{T}(&a, seed) && i == 777 && check_{T}(&b, seed + 1) && va_arg(ap, int) == 12345;
  va_end(ap);
  return ok;
}}
{s['vam']} {{
  va_list ap;
  int ok = 1;
  va_start(ap, seed);
  for (long k = 1; k <= 6; k++)
    ok = ok && va_arg(ap, long) == k;
  {T} a = va_arg(ap, {T});
  ok = ok && check_{T}(&a, seed) && va_arg(ap, int) == 12345;
  va_end(ap);
  return ok;
}}
"""


# long double varargs at odd stack offsets (16-byte aligned on x86-64).
VA_LD = """int {p}_va_ld(int n, ...) {{
  va_list ap;
  int ok = 1;
  va_start(ap, n);
  for (long k = 1; k <= 6; k++)
    ok = ok && va_arg(ap, long) == k;
  ok = ok && va_arg(ap, long double) == 2.5L && va_arg(ap, long) == 7
      && va_arg(ap, long double) == -3.25L && va_arg(ap, int) == 12345;
  va_end(ap);
  return ok;
}}
"""
VA_LD_CALL = "(0, 1L, 2L, 3L, 4L, 5L, 6L, 2.5L, 7L, -3.25L, 12345)"


def gen_host(out):
    w = out.write
    w('// Generated by test/mir-abi/gen.py - do not edit.\n#include "abi.h"\n\n')
    w(VA_LD.format(p="h"))
    w(f"int h_cb_va_ld(int (*f)(int, ...)) {{ return f{VA_LD_CALL}; }}\n\n")
    for name, body, members, flags in TYPES:
        T = name
        if "bitint" in flags:
            w("#ifdef HAVE_BITINT\n")
        w(bodies(T, "h"))
        # Host calling into JIT code through function pointers.
        w(f"""int h_cb_ret_{T}({T} (*f)(int), int seed) {{ {T} v = f(seed); return check_{T}(&v, seed); }}
int h_cb_arg_{T}(int (*f)({T}, int), int seed) {{ return f(mk_{T}(seed), seed); }}
int h_cb_two_{T}(int (*f)({T}, {T}, int), int seed) {{ return f(mk_{T}(seed), mk_{T}(seed + 1), seed); }}
int h_cb_mi_{T}(int (*f)(long, long, long, long, long, {T}, long, int), int seed) {{
  return f(1, 2, 3, 4, 5, mk_{T}(seed), 6, seed);
}}
int h_cb_m7_{T}(int (*f)(long, long, long, long, long, long, long, {T}, long, int), int seed) {{
  return f(1, 2, 3, 4, 5, 6, 7, mk_{T}(seed), 8, seed);
}}
int h_cb_mf_{T}(int (*f)(double, double, double, double, double, double, double, {T}, double, int), int seed) {{
  return f(1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5, mk_{T}(seed), 8.5, seed);
}}
int h_cb_rmi_{T}({T} (*f)(long, long, long, long, long, long, int), int seed) {{
  {T} v = f(1, 2, 3, 4, 5, 6, seed);
  return check_{T}(&v, seed);
}}
int h_cb_va_{T}(int (*f)(int, int, ...), int seed) {{
  return f(seed, 2, mk_{T}(seed), mk_{T}(seed + 1), 12345);
}}
int h_cb_va1_{T}(int (*f)(int, ...), int seed) {{
  return f(seed, mk_{T}(seed), 777, mk_{T}(seed + 1), 12345);
}}
int h_cb_vam_{T}(int (*f)(int, ...), int seed) {{
  return f(seed, 1L, 2L, 3L, 4L, 5L, 6L, mk_{T}(seed), 12345);
}}
""")
        if "bitint" in flags:
            w("#endif\n")
        w("\n")


def gen_jit(out):
    w = out.write
    w('// Generated by test/mir-abi/gen.py - do not edit.\n#include "abi.h"\n#include <stdio.h>\n\n')
    w("static int fails, checks;\n")
    w(VA_LD.format(p="j"))
    w("int h_va_ld(int n, ...);\nint h_cb_va_ld(int (*f)(int, ...));\n")
    w("static void ck(const char *t, const char *what, int ok) {\n"
      "  checks++;\n"
      "  if (!ok) { fails++; printf(\"FAIL %s %s\\n\", t, what); }\n}\n\n")
    for name, body, members, flags in TYPES:
        T = name
        guard = "bitint" in flags
        # Variadic HFAs on aarch64 still travel as MIR BLKs (MIR's va_arg
        # can't fetch them from the FP save area) - see codegen-mir.c.
        va_ok = "hfa" not in flags
        if guard:
            w("#ifdef HAVE_BITINT\n")
        w(bodies(T, "j"))
        hs = sig(T, "h")
        for k in ("ret", "arg", "two", "mi", "m7", "mf", "rmi", "va", "va1", "vam"):
            w(hs[k] + ";\n")
        w(f"""int h_cb_ret_{T}({T} (*f)(int), int seed);
int h_cb_arg_{T}(int (*f)({T}, int), int seed);
int h_cb_two_{T}(int (*f)({T}, {T}, int), int seed);
int h_cb_mi_{T}(int (*f)(long, long, long, long, long, {T}, long, int), int seed);
int h_cb_m7_{T}(int (*f)(long, long, long, long, long, long, long, {T}, long, int), int seed);
int h_cb_mf_{T}(int (*f)(double, double, double, double, double, double, double, {T}, double, int), int seed);
int h_cb_rmi_{T}({T} (*f)(long, long, long, long, long, long, int), int seed);
int h_cb_va_{T}(int (*f)(int, int, ...), int seed);
int h_cb_va1_{T}(int (*f)(int, ...), int seed);
int h_cb_vam_{T}(int (*f)(int, ...), int seed);

static void test_{T}(int s) {{
  {{ {T} v = h_ret_{T}(s); ck("{T}", "jit->host ret", check_{T}(&v, s)); }}
  {{ {T} v = h_rmi_{T}(1, 2, 3, 4, 5, 6, s); ck("{T}", "jit->host ret after 6 ints", check_{T}(&v, s)); }}
  ck("{T}", "jit->host arg", h_arg_{T}(mk_{T}(s), s));
  ck("{T}", "jit->host two args", h_two_{T}(mk_{T}(s), mk_{T}(s + 1), s));
  ck("{T}", "jit->host arg after 5 ints", h_mi_{T}(1, 2, 3, 4, 5, mk_{T}(s), 6, s));
  ck("{T}", "jit->host arg after 7 ints", h_m7_{T}(1, 2, 3, 4, 5, 6, 7, mk_{T}(s), 8, s));
  ck("{T}", "jit->host arg after 7 doubles", h_mf_{T}(1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5, mk_{T}(s), 8.5, s));
  ck("{T}", "host->jit ret", h_cb_ret_{T}(j_ret_{T}, s));
  ck("{T}", "host->jit ret after 6 ints", h_cb_rmi_{T}(j_rmi_{T}, s));
  ck("{T}", "host->jit arg", h_cb_arg_{T}(j_arg_{T}, s));
  ck("{T}", "host->jit two args", h_cb_two_{T}(j_two_{T}, s));
  ck("{T}", "host->jit arg after 5 ints", h_cb_mi_{T}(j_mi_{T}, s));
  ck("{T}", "host->jit arg after 7 ints", h_cb_m7_{T}(j_m7_{T}, s));
  ck("{T}", "host->jit arg after 7 doubles", h_cb_mf_{T}(j_mf_{T}, s));
  ck("{T}", "jit->jit va", j_va_{T}(s, 2, mk_{T}(s), mk_{T}(s + 1), 12345));
  ck("{T}", "jit->jit va odd", j_va1_{T}(s, mk_{T}(s), 777, mk_{T}(s + 1), 12345));
  ck("{T}", "jit->jit va after 6 longs", j_vam_{T}(s, 1L, 2L, 3L, 4L, 5L, 6L, mk_{T}(s), 12345));
""")
        w("#if 1\n" if va_ok else "#if !defined(__aarch64__)\n")
        w(f"""  ck("{T}", "jit->host va", h_va_{T}(s, 2, mk_{T}(s), mk_{T}(s + 1), 12345));
  ck("{T}", "host->jit va", h_cb_va_{T}(j_va_{T}, s));
  ck("{T}", "jit->host va odd", h_va1_{T}(s, mk_{T}(s), 777, mk_{T}(s + 1), 12345));
  ck("{T}", "host->jit va odd", h_cb_va1_{T}(j_va1_{T}, s));
  ck("{T}", "jit->host va after 6 longs", h_vam_{T}(s, 1L, 2L, 3L, 4L, 5L, 6L, mk_{T}(s), 12345));
  ck("{T}", "host->jit va after 6 longs", h_cb_vam_{T}(j_vam_{T}, s));
#endif
}}
""")
        if guard:
            w("#endif\n")
        w("\n")
    w("int main(void) {\n")
    w(f'  ck("long double", "jit->host va", h_va_ld{VA_LD_CALL});\n')
    w('  ck("long double", "host->jit va", h_cb_va_ld(j_va_ld));\n')
    w(f'  ck("long double", "jit->jit va", j_va_ld{VA_LD_CALL});\n')
    w("  for (int s = 1; s <= 3; s++) {\n")
    for name, body, members, flags in TYPES:
        if "bitint" in flags:
            w("#ifdef HAVE_BITINT\n")
        w(f"    test_{name}(s);\n")
        if "bitint" in flags:
            w("#endif\n")
    w("  }\n  printf(\"%d/%d checks passed\\n\", checks - fails, checks);\n"
      "  return fails != 0;\n}\n")


def main():
    outdir = sys.argv[1]
    bitint = "--bitint" in sys.argv[2:]
    os.makedirs(outdir, exist_ok=True)
    with open(os.path.join(outdir, "abi.h"), "w") as f:
        gen_header(f, bitint)
    with open(os.path.join(outdir, "host.c"), "w") as f:
        gen_host(f)
    with open(os.path.join(outdir, "jit.c"), "w") as f:
        gen_jit(f)


main()
